In [1]:
import sys

print(sys.executable)

c:\DataEngineeringProjects\fintrack-exchange-api-pipeline\venv\Scripts\python.exe

### Import Libraries

In [2]:
import os
from datetime import datetime, timezone

import pandas as pd
import requests #requests is a Python package used to communicate with web APIs. it will retrieve the latest exchange rates from the Exchange Rate API.
from dotenv import load_dotenv # python-dotenv reads values stored in a .env file. This prevents sensitive information such as database credentials from being hard-coded into your program.
from sqlalchemy import create_engine, text

### Load environment varialbles

In [3]:
load_dotenv() # Reads the .env file. Loads all variables into Python's environment.

True

### Define API endpoint

In [ ]:
# Using the open.er-api.com API for exchange rates, which does not require an API key.
BASE_CURRENCY = "USD"

API_URL = (
    f"https://open.er-api.com/v6/latest/{BASE_CURRENCY}"
)

print(API_URL)

https://open.er-api.com/v6/latest/USD

### Extraction

In [15]:
# Make the request 
import requests

response = requests.get(API_URL, timeout=30)

print("Status code:", response.status_code)

response.raise_for_status()

api_data = response.json()

print(api_data["result"])
print(api_data["base_code"])

Status code: 200
success
USD

In [ ]:
# Inspect the JSON response
# The exchange rates key i the business data in the JSON response
api_data

{'result': 'success',
 'provider': 'https://www.exchangerate-api.com',
 'documentation': 'https://www.exchangerate-api.com/docs/free',
 'terms_of_use': 'https://www.exchangerate-api.com/terms',
 'time_last_update_unix': 1783900951,
 'time_last_update_utc': 'Mon, 13 Jul 2026 00:02:31 +0000',
 'time_next_update_unix': 1783988701,
 'time_next_update_utc': 'Tue, 14 Jul 2026 00:25:01 +0000',
 'time_eol_unix': 0,
 'base_code': 'USD',
 'rates': {'USD': 1,
  'AED': 3.6725,
  'AFN': 65.222208,
  'ALL': 82.096933,
  'AMD': 367.251901,
  'ANG': 1.79,
  'AOA': 921.874613,
  'ARS': 1490.9024,
  'AUD': 1.440982,
  'AWG': 1.79,
  'AZN': 1.699568,
  'BAM': 1.71485,
  'BBD': 2,
  'BDT': 123.263755,
  'BGN': 1.71485,
  'BHD': 0.376,
  'BIF': 2988.954226,
  'BMD': 1,
  'BND': 1.292442,
  'BOB': 10.010534,
  'BRL': 5.111573,
  'BSD': 1,
  'BTN': 95.495903,
  'BWP': 13.788099,
  'BYN': 2.861896,
  'BZD': 2,
  'CAD': 1.41652,
  'CDF': 2288.184574,
  'CHF': 0.80929,
  'CLF': 0.023427,
  'CLP': 925.982638,
  'CNH': 6.785612,
  'CNY': 6.77996,
  'COP': 3276.378067,
  'CRC': 454.810252,
  'CUP': 24,
  'CVE': 96.67912,
  'CZK': 21.261978,
  'DJF': 177.721,
  'DKK': 6.541128,
  'DOP': 58.689505,
  'DZD': 133.157254,
  'EGP': 49.812111,
  'ERN': 15,
  'ETB': 159.536638,
  'EUR': 0.87679,
  'FJD': 2.232751,
  'FKP': 0.746979,
  'FOK': 6.5416,
  'GBP': 0.74699,
  'GEL': 2.631584,
  'GGP': 0.746979,
  'GHS': 11.463481,
  'GIP': 0.746979,
  'GMD': 74.282527,
  'GNF': 8788.658589,
  'GTQ': 7.626214,
  'GYD': 209.22092,
  'HKD': 7.83976,
  'HNL': 26.751911,
  'HRK': 6.606165,
  'HTG': 130.780624,
  'HUF': 312.703317,
  'IDR': 18071.147428,
  'ILS': 3.011515,
  'IMP': 0.746979,
  'INR': 95.492784,
  'IQD': 1309.688551,
  'IRR': 1152906.965652,
  'ISK': 125.489597,
  'JEP': 0.746979,
  'JMD': 158.690138,
  'JOD': 0.709,
  'JPY': 161.879691,
  'KES': 129.182165,
  'KGS': 87.478026,
  'KHR': 4047.980216,
  'KID': 1.440943,
  'KMF': 431.351826,
  'KRW': 1501.331727,
  'KWD': 0.308938,
  'KYD': 0.833333,
  'KZT': 471.544404,
  'LAK': 22350.333962,
  'LBP': 89500,
  'LKR': 335.295769,
  'LRD': 181.248657,
  'LSL': 16.352791,
  'LYD': 6.396533,
  'MAD': 9.336804,
  'MDL': 17.505753,
  'MGA': 4272.199141,
  'MKD': 53.92275,
  'MMK': 2101.655449,
  'MNT': 3577.268005,
  'MOP': 8.074905,
  'MRU': 40.086544,
  'MUR': 47.053589,
  'MVR': 15.437878,
  'MWK': 1740.2922,
  'MXN': 17.513814,
  'MYR': 4.069842,
  'MZN': 63.584712,
  'NAD': 16.352791,
  'NGN': 1375.906868,
  'NIO': 36.77894,
  'NOK': 9.778804,
  'NPR': 152.793445,
  'NZD': 1.73683,
  'OMR': 0.384497,
  'PAB': 1,
  'PEN': 3.394858,
  'PGK': 4.426063,
  'PHP': 61.551685,
  'PKR': 278.044182,
  'PLN': 3.802326,
  'PYG': 6061.444415,
  'QAR': 3.64,
  'RON': 4.578942,
  'RSD': 102.653508,
  'RUB': 76.76121,
  'RWF': 1467.372158,
  'SAR': 3.75,
  'SBD': 7.974259,
  'SCR': 14.660914,
  'SDG': 458.890393,
  'SEK': 9.676007,
  'SGD': 1.292444,
  'SHP': 0.746979,
  'SLE': 24.328197,
  'SLL': 24328.196854,
  'SOS': 572.021989,
  'SRD': 37.708744,
  'SSP': 4784.011977,
  'STN': 21.481326,
  'SYP': 121.604348,
  'SZL': 16.352791,
  'THB': 33.340175,
  'TJS': 9.238105,
  'TMT': 3.500522,
  'TND': 2.94058,
  'TOP': 2.386598,
  'TRY': 47.026116,
  'TTD': 6.782195,
  'TVD': 1.440943,
  'TWD': 32.070543,
  'TZS': 2627.865783,
  'UAH': 44.507324,
  'UGX': 3659.341803,
  'UYU': 40.170162,
  'UZS': 12232.568466,
  'VES': 721.3456,
  'VND': 26191.273042,
  'VUV': 119.898311,
  'WST': 2.726398,
  'XAF': 575.135768,
  'XCD': 2.7,
  'XCG': 1.79,
  'XDR': 0.736639,
  'XOF': 575.135768,
  'XPF': 104.628964,
  'YER': 237.567571,
  'ZAR': 16.352736,
  'ZMW': 18.048864,
  'ZWG': 26.7159,
  'ZWL': 26.7159}}

- result: This confirms that the API request was successful. If the API key were invalid or the request failed, this value would typically contain an error instead.
- provider: This tells us the organization that provides the exchange-rate data.
- documentation: This is simply a link to the API documentation. 
- terms_of_use: This points to the API's terms and conditions
- The below are timestamps:
    - time_last_update_unix
    - time_last_update_utc
    - time_next_update_unix
    - time_next_update_utc
* The above timestamps inform when the exchange rates were last updated, when the next update will occur
* The above fields are useful in production pipelines because they tell us whether our data is fresh.
- base_code 'USD': This is extremely important. It tells us that all exchange rates are relative to the US Dollar. e.g, "NGN": 1375.906868. 1 USD = 1375.906868 Nigerian Naira 
- rates: This is the business data. Every key is a currency. Every value is its exchange rate. This is the business data actually needed. Everything else is metadata.

In [ ]:
# Extract the exchange rates from the API response
# The exchange rates key i the business data in the JSON response
api_data["rates"]

{'USD': 1,
 'AED': 3.6725,
 'AFN': 65.222208,
 'ALL': 82.096933,
 'AMD': 367.251901,
 'ANG': 1.79,
 'AOA': 921.874613,
 'ARS': 1490.9024,
 'AUD': 1.440982,
 'AWG': 1.79,
 'AZN': 1.699568,
 'BAM': 1.71485,
 'BBD': 2,
 'BDT': 123.263755,
 'BGN': 1.71485,
 'BHD': 0.376,
 'BIF': 2988.954226,
 'BMD': 1,
 'BND': 1.292442,
 'BOB': 10.010534,
 'BRL': 5.111573,
 'BSD': 1,
 'BTN': 95.495903,
 'BWP': 13.788099,
 'BYN': 2.861896,
 'BZD': 2,
 'CAD': 1.41652,
 'CDF': 2288.184574,
 'CHF': 0.80929,
 'CLF': 0.023427,
 'CLP': 925.982638,
 'CNH': 6.785612,
 'CNY': 6.77996,
 'COP': 3276.378067,
 'CRC': 454.810252,
 'CUP': 24,
 'CVE': 96.67912,
 'CZK': 21.261978,
 'DJF': 177.721,
 'DKK': 6.541128,
 'DOP': 58.689505,
 'DZD': 133.157254,
 'EGP': 49.812111,
 'ERN': 15,
 'ETB': 159.536638,
 'EUR': 0.87679,
 'FJD': 2.232751,
 'FKP': 0.746979,
 'FOK': 6.5416,
 'GBP': 0.74699,
 'GEL': 2.631584,
 'GGP': 0.746979,
 'GHS': 11.463481,
 'GIP': 0.746979,
 'GMD': 74.282527,
 'GNF': 8788.658589,
 'GTQ': 7.626214,
 'GYD': 209.22092,
 'HKD': 7.83976,
 'HNL': 26.751911,
 'HRK': 6.606165,
 'HTG': 130.780624,
 'HUF': 312.703317,
 'IDR': 18071.147428,
 'ILS': 3.011515,
 'IMP': 0.746979,
 'INR': 95.492784,
 'IQD': 1309.688551,
 'IRR': 1152906.965652,
 'ISK': 125.489597,
 'JEP': 0.746979,
 'JMD': 158.690138,
 'JOD': 0.709,
 'JPY': 161.879691,
 'KES': 129.182165,
 'KGS': 87.478026,
 'KHR': 4047.980216,
 'KID': 1.440943,
 'KMF': 431.351826,
 'KRW': 1501.331727,
 'KWD': 0.308938,
 'KYD': 0.833333,
 'KZT': 471.544404,
 'LAK': 22350.333962,
 'LBP': 89500,
 'LKR': 335.295769,
 'LRD': 181.248657,
 'LSL': 16.352791,
 'LYD': 6.396533,
 'MAD': 9.336804,
 'MDL': 17.505753,
 'MGA': 4272.199141,
 'MKD': 53.92275,
 'MMK': 2101.655449,
 'MNT': 3577.268005,
 'MOP': 8.074905,
 'MRU': 40.086544,
 'MUR': 47.053589,
 'MVR': 15.437878,
 'MWK': 1740.2922,
 'MXN': 17.513814,
 'MYR': 4.069842,
 'MZN': 63.584712,
 'NAD': 16.352791,
 'NGN': 1375.906868,
 'NIO': 36.77894,
 'NOK': 9.778804,
 'NPR': 152.793445,
 'NZD': 1.73683,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.394858,
 'PGK': 4.426063,
 'PHP': 61.551685,
 'PKR': 278.044182,
 'PLN': 3.802326,
 'PYG': 6061.444415,
 'QAR': 3.64,
 'RON': 4.578942,
 'RSD': 102.653508,
 'RUB': 76.76121,
 'RWF': 1467.372158,
 'SAR': 3.75,
 'SBD': 7.974259,
 'SCR': 14.660914,
 'SDG': 458.890393,
 'SEK': 9.676007,
 'SGD': 1.292444,
 'SHP': 0.746979,
 'SLE': 24.328197,
 'SLL': 24328.196854,
 'SOS': 572.021989,
 'SRD': 37.708744,
 'SSP': 4784.011977,
 'STN': 21.481326,
 'SYP': 121.604348,
 'SZL': 16.352791,
 'THB': 33.340175,
 'TJS': 9.238105,
 'TMT': 3.500522,
 'TND': 2.94058,
 'TOP': 2.386598,
 'TRY': 47.026116,
 'TTD': 6.782195,
 'TVD': 1.440943,
 'TWD': 32.070543,
 'TZS': 2627.865783,
 'UAH': 44.507324,
 'UGX': 3659.341803,
 'UYU': 40.170162,
 'UZS': 12232.568466,
 'VES': 721.3456,
 'VND': 26191.273042,
 'VUV': 119.898311,
 'WST': 2.726398,
 'XAF': 575.135768,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.736639,
 'XOF': 575.135768,
 'XPF': 104.628964,
 'YER': 237.567571,
 'ZAR': 16.352736,
 'ZMW': 18.048864,
 'ZWG': 26.7159,
 'ZWL': 26.7159}

### Inspect the structure of the data first before transforming

In [19]:
type(api_data)

dict

In [20]:
type(api_data["rates"])

dict

In [21]:
api_data.keys()

dict_keys(['result', 'provider', 'documentation', 'terms_of_use', 'time_last_update_unix', 'time_last_update_utc', 'time_next_update_unix', 'time_next_update_utc', 'time_eol_unix', 'base_code', 'rates'])

In [23]:
api_data.get("base_code")

'USD'

## Save the raw API response. 
### This preserves the original source data
- Auditability
- Reprocessing
- Debugging
- Evidence of the original source
- Protection from future API changes

In [ ]:
import json
from pathlib import Path

raw_folder = Path("../data/raw_data")
raw_folder.mkdir(parents=True, exist_ok=True)

extraction_timestamp = datetime.now(timezone.utc)
raw_filename = (
    f"exchange_rates_"
    f"{extraction_timestamp:%Y%m%d_%H%M%S}.json"
)

raw_path = raw_folder / raw_filename

with open(raw_path, "w", encoding="utf-8") as file:
    json.dump(api_data, file, indent=4)

print(f"Raw response saved to: {raw_path}")

Raw response saved to: ..\data\raw_data\exchange_rates_20260713_164339.json

## Transformation

In [43]:
# Extract the exchange rates dictionary from the JSON response
rates = api_data["rates"]

# Display the dictionary
rates

{'USD': 1,
 'AED': 3.6725,
 'AFN': 65.222208,
 'ALL': 82.096933,
 'AMD': 367.251901,
 'ANG': 1.79,
 'AOA': 921.874613,
 'ARS': 1490.9024,
 'AUD': 1.440982,
 'AWG': 1.79,
 'AZN': 1.699568,
 'BAM': 1.71485,
 'BBD': 2,
 'BDT': 123.263755,
 'BGN': 1.71485,
 'BHD': 0.376,
 'BIF': 2988.954226,
 'BMD': 1,
 'BND': 1.292442,
 'BOB': 10.010534,
 'BRL': 5.111573,
 'BSD': 1,
 'BTN': 95.495903,
 'BWP': 13.788099,
 'BYN': 2.861896,
 'BZD': 2,
 'CAD': 1.41652,
 'CDF': 2288.184574,
 'CHF': 0.80929,
 'CLF': 0.023427,
 'CLP': 925.982638,
 'CNH': 6.785612,
 'CNY': 6.77996,
 'COP': 3276.378067,
 'CRC': 454.810252,
 'CUP': 24,
 'CVE': 96.67912,
 'CZK': 21.261978,
 'DJF': 177.721,
 'DKK': 6.541128,
 'DOP': 58.689505,
 'DZD': 133.157254,
 'EGP': 49.812111,
 'ERN': 15,
 'ETB': 159.536638,
 'EUR': 0.87679,
 'FJD': 2.232751,
 'FKP': 0.746979,
 'FOK': 6.5416,
 'GBP': 0.74699,
 'GEL': 2.631584,
 'GGP': 0.746979,
 'GHS': 11.463481,
 'GIP': 0.746979,
 'GMD': 74.282527,
 'GNF': 8788.658589,
 'GTQ': 7.626214,
 'GYD': 209.22092,
 'HKD': 7.83976,
 'HNL': 26.751911,
 'HRK': 6.606165,
 'HTG': 130.780624,
 'HUF': 312.703317,
 'IDR': 18071.147428,
 'ILS': 3.011515,
 'IMP': 0.746979,
 'INR': 95.492784,
 'IQD': 1309.688551,
 'IRR': 1152906.965652,
 'ISK': 125.489597,
 'JEP': 0.746979,
 'JMD': 158.690138,
 'JOD': 0.709,
 'JPY': 161.879691,
 'KES': 129.182165,
 'KGS': 87.478026,
 'KHR': 4047.980216,
 'KID': 1.440943,
 'KMF': 431.351826,
 'KRW': 1501.331727,
 'KWD': 0.308938,
 'KYD': 0.833333,
 'KZT': 471.544404,
 'LAK': 22350.333962,
 'LBP': 89500,
 'LKR': 335.295769,
 'LRD': 181.248657,
 'LSL': 16.352791,
 'LYD': 6.396533,
 'MAD': 9.336804,
 'MDL': 17.505753,
 'MGA': 4272.199141,
 'MKD': 53.92275,
 'MMK': 2101.655449,
 'MNT': 3577.268005,
 'MOP': 8.074905,
 'MRU': 40.086544,
 'MUR': 47.053589,
 'MVR': 15.437878,
 'MWK': 1740.2922,
 'MXN': 17.513814,
 'MYR': 4.069842,
 'MZN': 63.584712,
 'NAD': 16.352791,
 'NGN': 1375.906868,
 'NIO': 36.77894,
 'NOK': 9.778804,
 'NPR': 152.793445,
 'NZD': 1.73683,
 'OMR': 0.384497,
 'PAB': 1,
 'PEN': 3.394858,
 'PGK': 4.426063,
 'PHP': 61.551685,
 'PKR': 278.044182,
 'PLN': 3.802326,
 'PYG': 6061.444415,
 'QAR': 3.64,
 'RON': 4.578942,
 'RSD': 102.653508,
 'RUB': 76.76121,
 'RWF': 1467.372158,
 'SAR': 3.75,
 'SBD': 7.974259,
 'SCR': 14.660914,
 'SDG': 458.890393,
 'SEK': 9.676007,
 'SGD': 1.292444,
 'SHP': 0.746979,
 'SLE': 24.328197,
 'SLL': 24328.196854,
 'SOS': 572.021989,
 'SRD': 37.708744,
 'SSP': 4784.011977,
 'STN': 21.481326,
 'SYP': 121.604348,
 'SZL': 16.352791,
 'THB': 33.340175,
 'TJS': 9.238105,
 'TMT': 3.500522,
 'TND': 2.94058,
 'TOP': 2.386598,
 'TRY': 47.026116,
 'TTD': 6.782195,
 'TVD': 1.440943,
 'TWD': 32.070543,
 'TZS': 2627.865783,
 'UAH': 44.507324,
 'UGX': 3659.341803,
 'UYU': 40.170162,
 'UZS': 12232.568466,
 'VES': 721.3456,
 'VND': 26191.273042,
 'VUV': 119.898311,
 'WST': 2.726398,
 'XAF': 575.135768,
 'XCD': 2.7,
 'XCG': 1.79,
 'XDR': 0.736639,
 'XOF': 575.135768,
 'XPF': 104.628964,
 'YER': 237.567571,
 'ZAR': 16.352736,
 'ZMW': 18.048864,
 'ZWG': 26.7159,
 'ZWL': 26.7159}

In [ ]:
# Convert the dictionary into a DataFrame
exchange_rates = pd.DataFrame( #pd.DataFrames converts into a table
    list(rates.items()), # Converts the tuples into a list. N.B rates.items() converts each dict into a tuple first. then list(rates.item()) converts the tuples into a list
    columns=["currency_code", "exchange_rate"] # This assigns meaningful column names
)

# Display the first five rows
exchange_rates.head()

  currency_code  exchange_rate
0           USD       1.000000
1           AED       3.672500
2           AFN      65.222208
3           ALL      82.096933
4           AMD     367.251901

In [ ]:
# Add the base currency to every row
# Every exchange rate uses USD.
# Instead of keeping the information separate, add it to every row. 
exchange_rates["base_currency"] = api_data["base_code"]

exchange_rates.head()

  currency_code  exchange_rate base_currency
0           USD       1.000000           USD
1           AED       3.672500           USD
2           AFN      65.222208           USD
3           ALL      82.096933           USD
4           AMD     367.251901           USD

In [ ]:
# Add extraction timestamp. This records when the data was collected
# Add the timestamp showing when the exchange rates were retrieved
exchange_rates["retrieved_at"] = api_data["time_last_update_utc"]

exchange_rates.head()

  currency_code  exchange_rate base_currency                     retrieved_at
0           USD       1.000000           USD  Mon, 13 Jul 2026 00:02:31 +0000
1           AED       3.672500           USD  Mon, 13 Jul 2026 00:02:31 +0000
2           AFN      65.222208           USD  Mon, 13 Jul 2026 00:02:31 +0000
3           ALL      82.096933           USD  Mon, 13 Jul 2026 00:02:31 +0000
4           AMD     367.251901           USD  Mon, 13 Jul 2026 00:02:31 +0000

In [30]:
# Reorder/rearrange the columns
# This makes the dataset more organized before exporting or loading into PostgreSQL
exchange_rates = exchange_rates[
    [
        "base_currency",
        "currency_code",
        "exchange_rate",
        "retrieved_at"
    ]
]

exchange_rates.head()

  base_currency currency_code  exchange_rate                     retrieved_at
0           USD           USD       1.000000  Mon, 13 Jul 2026 00:02:31 +0000
1           USD           AED       3.672500  Mon, 13 Jul 2026 00:02:31 +0000
2           USD           AFN      65.222208  Mon, 13 Jul 2026 00:02:31 +0000
3           USD           ALL      82.096933  Mon, 13 Jul 2026 00:02:31 +0000
4           USD           AMD     367.251901  Mon, 13 Jul 2026 00:02:31 +0000

In [31]:
# Display the first 10 rows
exchange_rates.head(10)

  base_currency currency_code  exchange_rate                     retrieved_at
0           USD           USD       1.000000  Mon, 13 Jul 2026 00:02:31 +0000
1           USD           AED       3.672500  Mon, 13 Jul 2026 00:02:31 +0000
2           USD           AFN      65.222208  Mon, 13 Jul 2026 00:02:31 +0000
3           USD           ALL      82.096933  Mon, 13 Jul 2026 00:02:31 +0000
4           USD           AMD     367.251901  Mon, 13 Jul 2026 00:02:31 +0000
5           USD           ANG       1.790000  Mon, 13 Jul 2026 00:02:31 +0000
6           USD           AOA     921.874613  Mon, 13 Jul 2026 00:02:31 +0000
7           USD           ARS    1490.902400  Mon, 13 Jul 2026 00:02:31 +0000
8           USD           AUD       1.440982  Mon, 13 Jul 2026 00:02:31 +0000
9           USD           AWG       1.790000  Mon, 13 Jul 2026 00:02:31 +0000

In [32]:
# Display the shape
exchange_rates.shape

(166, 4)

In [33]:
# Display the column names
exchange_rates.columns

Index(['base_currency', 'currency_code', 'exchange_rate', 'retrieved_at'], dtype='str')

In [34]:
# Display data types
exchange_rates.dtypes

base_currency        str
currency_code        str
exchange_rate    float64
retrieved_at         str
dtype: object

In [35]:
# Display general information
exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   base_currency  166 non-null    str
 1   currency_code  166 non-null    str
 2   exchange_rate  166 non-null    float64
 3   retrieved_at   166 non-null    str
dtypes: float64(1), str(3)
memory usage: 5.3 KB

In [36]:
# Display summary statistics
exchange_rates.describe()

       exchange_rate
count   1.660000e+02
mean    8.522752e+03
std     8.970162e+04
min     2.342700e-02
25%     2.958314e+00
50%     2.274066e+01
75%     1.803667e+02
max     1.152907e+06

In [44]:
# Check for missing values
exchange_rates.isnull().sum()

base_currency    0
currency_code    0
exchange_rate    0
retrieved_at     0
dtype: int64

In [40]:
# Check for duplicate rows
exchange_rates.duplicated().sum()

np.int64(0)

##### The API returns data in JSON format, where the exchange rates are stored as a Python dictionary. While dictionaries are excellent for storing key-value pairs, they are not ideal for data analysis. By converting the dictionary into a Pandas DataFrame, we transform the data into rows and columns, making it easier to explore, clean, export as CSV, and load into PostgreSQL for analysis. This transformation step is a core part of every ETL pipeline.

##### The Transformation step of the ETL pipeline has been completed. The API returned a nested JSON object, but the business data (rates) has been extracted and transformed into a structured Pandas DataFrame. The data is now in a format that is ready for exploration, cleaning, validation, and eventually loading into the database(PostgreSQL).

In [42]:
exchange_rates

,base_currency,currency_code,exchange_rate,retrieved_at
0,USD,USD,1.000000,"Mon, 13 Jul 2026 00:02:31 +0000"
1,USD,AED,3.672500,"Mon, 13 Jul 2026 00:02:31 +0000"
2,USD,AFN,65.222208,"Mon, 13 Jul 2026 00:02:31 +0000"
3,USD,ALL,82.096933,"Mon, 13 Jul 2026 00:02:31 +0000"
4,USD,AMD,367.251901,"Mon, 13 Jul 2026 00:02:31 +0000"
...,...,...,...,...
161,USD,YER,237.567571,"Mon, 13 Jul 2026 00:02:31 +0000"
162,USD,ZAR,16.352736,"Mon, 13 Jul 2026 00:02:31 +0000"
163,USD,ZMW,18.048864,"Mon, 13 Jul 2026 00:02:31 +0000"
164,USD,ZWG,26.715900,"Mon, 13 Jul 2026 00:02:31 +0000"
165,USD,ZWL,26.715900,"Mon, 13 Jul 2026 00:02:31 +0000"

## DATA CLEANING: Although the data is already very clean (which is common with good APIs), every ETL pipeline data must be validated loading it

In [45]:
# Check for Blanks
(exchange_rates == "").sum()

base_currency    0
currency_code    0
exchange_rate    0
retrieved_at     0
dtype: int64

In [82]:
exchange_rates.isnull().sum()

base_currency    0
currency_code    0
exchange_rate    0
retrieved_at     0
dtype: int64

In [46]:
# Remove leading/trailing spaces
exchange_rates["currency_code"] = (exchange_rates["currency_code"].str.strip())

exchange_rates["base_currency"] = (exchange_rates["base_currency"].str.strip())

In [52]:
# Ensure exchange_rate column is numeric, converting any non-numeric values to NaN
exchange_rates["exchange_rate"] = pd.to_numeric(
    exchange_rates["exchange_rate"],
    errors="coerce"
)

In [48]:
exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   base_currency  166 non-null    str
 1   currency_code  166 non-null    str
 2   exchange_rate  166 non-null    float64
 3   retrieved_at   166 non-null    str
dtypes: float64(1), str(3)
memory usage: 5.3 KB

In [49]:
# Convert retrieved_at to datetime data type
exchange_rates["retrieved_at"] = pd.to_datetime(
    exchange_rates["retrieved_at"]
)

In [53]:
exchange_rates.dtypes

base_currency                    str
currency_code                    str
exchange_rate                float64
retrieved_at     datetime64[us, UTC]
dtype: object

## Business Validation: It is not enough to clean and transform data, business validation is equally important

In [81]:
# Check for unique currency codes
exchange_rates["currency_code"].nunique()

166

In [55]:
# Check duplicate currency codes 
exchange_rates["currency_code"].duplicated().sum()

np.int64(0)

In [56]:
# Lowest exchange rate
exchange_rates.nsmallest(10, "exchange_rate")

    base_currency currency_code  exchange_rate              retrieved_at
29            USD           CLF       0.023427 2026-07-13 00:02:31+00:00
80            USD           KWD       0.308938 2026-07-13 00:02:31+00:00
15            USD           BHD       0.376000 2026-07-13 00:02:31+00:00
109           USD           OMR       0.384497 2026-07-13 00:02:31+00:00
72            USD           JOD       0.709000 2026-07-13 00:02:31+00:00
158           USD           XDR       0.736639 2026-07-13 00:02:31+00:00
47            USD           FKP       0.746979 2026-07-13 00:02:31+00:00
51            USD           GGP       0.746979 2026-07-13 00:02:31+00:00
53            USD           GIP       0.746979 2026-07-13 00:02:31+00:00
65            USD           IMP       0.746979 2026-07-13 00:02:31+00:00

In [57]:
# Highest exchange rate 
exchange_rates.nlargest(10, "exchange_rate")

    base_currency currency_code  exchange_rate              retrieved_at
68            USD           IRR   1.152907e+06 2026-07-13 00:02:31+00:00
84            USD           LBP   8.950000e+04 2026-07-13 00:02:31+00:00
152           USD           VND   2.619127e+04 2026-07-13 00:02:31+00:00
130           USD           SLL   2.432820e+04 2026-07-13 00:02:31+00:00
83            USD           LAK   2.235033e+04 2026-07-13 00:02:31+00:00
63            USD           IDR   1.807115e+04 2026-07-13 00:02:31+00:00
150           USD           UZS   1.223257e+04 2026-07-13 00:02:31+00:00
55            USD           GNF   8.788659e+03 2026-07-13 00:02:31+00:00
116           USD           PYG   6.061444e+03 2026-07-13 00:02:31+00:00
133           USD           SSP   4.784012e+03 2026-07-13 00:02:31+00:00

## Export Clean Data

In [58]:
exchange_rates.to_csv("../data/cleaned_data/exchange_rates.csv", index=False)

print("Export successful.")

Export successful.

## Connect to PosgreSQL

## Load the cleaned data into Postgres

In [ ]:
# Load the environment variables from the .env file
import os
from dotenv import load_dotenv

load_dotenv("../.env", override=True)

print("Database user:", os.getenv("DB_USER"))
print("Database host:", os.getenv("DB_HOST"))
print("Database name:", os.getenv("DB_NAME"))
print("Password loaded:", bool(os.getenv("DB_PASSWORD")))

Database user: postgres
Database host: localhost
Database name: fintrack_exchange_db
Password loaded: True

In [ ]:
# Create the engine for PostgreSQL connection using SQLAlchemy
from sqlalchemy import URL, create_engine

DATABASE_URL = URL.create(
    drivername="postgresql+psycopg2",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME")
)

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True
)

print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/fintrack_exchange_db)

In [ ]:
# Test the connection to PostgreSQL

from sqlalchemy import text

try:
    with engine.connect() as conn:
        result = conn.execute(
            text("SELECT current_database(), current_user, version();")
        )
        print(result.fetchone())

    print("PostgreSQL connection successful.")

except Exception as error:
    print("PostgreSQL connection failed:")
    print(error)

('fintrack_exchange_db', 'postgres', 'PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35226, 64-bit')
PostgreSQL connection successful.

##### The Extract and Transform process have been completed

## Load the DataFrame to Postgres

In [ ]:
# Load the transformed exchange-rate data into PostgreSQL
rows_loaded = exchange_rates.to_sql(
    name="exchange_rates",
    con=engine,
    if_exists="replace", # This line deletes existing exchange_rates table that already exists and create a new table and loads the current DataFrames into it.
    index=False
)

print(f"{rows_loaded} rows loaded successfully.")

166 rows loaded successfully.

### Verify the Load from Python

In [76]:
verification = pd.read_sql(
    """
    SELECT COUNT(*) AS total_rows
    FROM exchange_rates;
    """,
    con=engine
)

verification

   total_rows
0         166

In [77]:
pd.read_sql(
    """
    SELECT *
    FROM exchange_rates
    LIMIT 10;
    """,
    con=engine
)

  base_currency currency_code  exchange_rate              retrieved_at
0           USD           USD       1.000000 2026-07-13 00:02:31+00:00
1           USD           AED       3.672500 2026-07-13 00:02:31+00:00
2           USD           AFN      65.222208 2026-07-13 00:02:31+00:00
3           USD           ALL      82.096933 2026-07-13 00:02:31+00:00
4           USD           AMD     367.251901 2026-07-13 00:02:31+00:00
5           USD           ANG       1.790000 2026-07-13 00:02:31+00:00
6           USD           AOA     921.874613 2026-07-13 00:02:31+00:00
7           USD           ARS    1490.902400 2026-07-13 00:02:31+00:00
8           USD           AUD       1.440982 2026-07-13 00:02:31+00:00
9           USD           AWG       1.790000 2026-07-13 00:02:31+00:00

In [79]:
exchange_rates["retrieved_at"] = pd.to_datetime(
    exchange_rates["retrieved_at"],
    utc=True
)

exchange_rates.dtypes

base_currency                    str
currency_code                    str
exchange_rate                float64
retrieved_at     datetime64[us, UTC]
dtype: object